<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Translator\Form\TranslateForm $form
 * @var \Translator\Api\Representation\TranslateRepresentation $translate
 * @var \Translator\Api\Representation\TranslateRepresentation $resource
 * @var string $action "add" or "edit"
 * @var string $submitLabel
 * @var string $deleteButton
 */

$translation = $translate;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');

$form->prepare();
?>

<?= $this->form()->openTag($form) ?>

<?php $this->trigger("view.$action.form.before", ['form' => $form]); ?>

<?= $this->formCollection($form) ?>

<div id="page-actions">
    <?= $deleteButton ?? '' ?>
    <?= $this->cancelButton() ?>
    <button type="submit" name="translation-submit" class="button"><?= $escape($submitLabel) ?></button>
</div>

<?php $this->trigger("view.$action.form.after", ['form' => $form]); ?>

<?= $this->form()->closeTag(); ?>
