<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Translate\Api\Representation\TranslateRepresentation $translate
 * @var \Translate\Api\Representation\TranslateRepresentation $resource
 */

$translation = $translate;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'translations show');

$this->headLink()
    ->appendStylesheet($assetUrl('css/translate-admin.css', 'Translate'));
?>

<?= $this->pageTitle(null, 1, $translate('Translations')) ?>

<div id="page-actions">
    <?php if ($translation->userIsAllowed('update')): ?>
    <?= $translation->link($translate('Edit translation'), 'edit', ['class' => 'button']) ?>
    <?php endif; ?>
</div>

<?php $this->trigger('view.show.before'); ?>

<div id="item-metadata">
    <dl class="translation-resource">
        <div class="meta-group">
            <dt><?= $translate('ID') ?></dt>
            <dd class="value"><?= $translation->id() ?></dd>
        </div>
        <div class="meta-group">
            <dt><?= $translate('Language source') ?></dt>
            <dd class="value"><?= $escape($translation->langSource()) ?></dd>
        </div>
        <div class="meta-group">
            <dt><?= $translate('Language translation') ?></dt>
            <dd class="value"><?= $escape($translation->langTranslation()) ?></dd>
        </div>
        <div class="meta-group">
            <dt><?= $translate('Status') ?></dt>
            <dd class="value"><?= $escape(sprintf($translate('Is automatic: %s'), $translation->automatic() ? $translate('yes') : $translate('no'))) ?></dd>
            <dd class="value"><?= $escape(sprintf($translate('Is reviewed: %s'), $translation->reviewed() ? $translate('yes') : $translate('no'))) ?></dd>
        </div>
        <div class="meta-group">
            <dt><?= $translate('String') ?></dt>
            <dd class="value"><?= $escape($translation->string()) ?></dd>
        </div>
        <div class="meta-group">
            <dt><?= $translate('Translation') ?></dt>
            <dd class="value"><?= $escape($translation->translation()) ?></dd>
        </div>
    </dl>
</div>

<?php $this->trigger('view.show.after'); ?>
