<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Translate\Api\Representation\TranslateRepresentation $translate
 * @var \Translate\Api\Representation\TranslateRepresentation $resource
 * @var bool $linkTitle
 */

$translation = $translate;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$this->htmlElement('body')->appendAttribute('class', 'translations show');
?>

<div class="resource-details">
    <?php if ($linkTitle): ?>
    <h3 class="o-title"><?= $resource->link($resource->displayTitle()) ?></h3>
    <?php else: ?>
    <h3 class="o-title"><?= $escape($resource->displayTitle()) ?></h3>
    <?php endif; ?>
    <div class="meta-group">
        <h4><?= $translate('ID') ?></h4>
        <div class="value"><?= $resource->id() ?></div>
    </div>
    <div class="meta-group">
        <h4><?= $translate('Language source') ?></h4>
        <div class="value"><?= $escape($resource->langSource()) ?></div>
    </div>
    <div class="meta-group">
        <h4><?= $translate('Language translation') ?></h4>
        <div class="value"><?= $escape($resource->langTranslation()) ?></div>
    </div>
    <div class="meta-group">
        <h4><?= $translate('Status') ?></h4>
        <div class="value"><?= $escape(sprintf($translate('Is automatic: %s'), $translation->automatic() ? $translate('yes') : $translate('no'))) ?></div>
        <div class="value"><?= $escape(sprintf($translate('Is reviewed: %s'), $translation->reviewed() ? $translate('yes') : $translate('no'))) ?></div>
    </div>
    <div class="meta-group">
        <h4><?= $translate('String') ?></h4>
        <div class="value"><?= $escape($resource->string()) ?></div>
    </div>
    <div class="meta-group">
        <h4><?= $translate('Translation') ?></h4>
        <div class="value"><?= $escape($resource->translation()) ?></div>
    </div>
    <?php $this->trigger('view.details', array('entity' => $resource)); ?>
</div>
